- alias: Welcome
####################
  trigger:
    platform: state
    entity_id: group.personal_devices
    to: "home"
  condition:
    - condition: state
      entity_id: input_boolean.daylight
      state: "off"
    - condition: state
      entity_id: input_boolean.in_bed
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.basic_light

- alias: Goodbye
####################
  trigger:
    platform: state         
    entity_id: group.personal_devices
    to: "not_home"
  action:
    - service: scene.turn_on
      entity_id: scene.all_off

- alias: Low light
####################
  trigger:
    platform: state
    entity_id: input_boolean.daylight
    to: "off"
    for:
      minutes: 2
  condition:
    - condition: state
      entity_id: group.personal_devices
      state: "home"
    - condition: state
      entity_id: input_boolean.in_bed
      state: "off"
  action:
    - service: scene.turn_on
      entity_id: scene.basic_light

- alias: Daylight
####################
  trigger:
    platform: state
    entity_id: input_boolean.daylight
    to: "on"
    for:
      minutes: 2
  action:
    service: light.turn_off

#~ - alias: Anti Anti Darkness
#~ ####################
  #~ trigger:
    #~ platform: state
    #~ entity_id: light.mood
    #~ to: "off"
  #~ action:
    #~ - service: script.turn_on
      #~ entity_id: script.pause_anti_darkness

- alias: Daylight on
####################
  trigger:
    platform: numeric_state
    entity_id: sensor.indoor_light
    above: 80

  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.daylight
  
- alias: Daylight off
####################
  trigger:
    platform: numeric_state
    entity_id: sensor.indoor_light
    below: 30

  action:
    service: input_boolean.turn_off
    entity_id: input_boolean.daylight

- alias: Daylight init
####################
  trigger:
    platform: state
    entity_id: sensor.indoor_light
    
  condition:
    condition: numeric_state
    entity_id: sensor.indoor_light
    above: 80
    
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.daylight
    - service: automation.turn_off
      entity_id: automation.daylight_init

- alias: Pause music for TV
####################
  trigger:
    platform: state
    entity_id: media_player.Lund265
    to: "playing"
  condition:
    condition: state
    entity_id: media_player.MPD
    state: "playing"
  action:
    service: media_player.media_pause
    entity_id: media_player.MPD

- alias: morning_preset
####################
  trigger:
    platform: state
    entity_id: input_select.transport
  action:
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.light_on_hour
        value: '{% if is_state("input_select.transport", "Car") %} {{5|float}} {% elif is_state("input_select.transport", "Bike") %} {{5|float}} {% endif %}'
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.light_on_minute
        value: '{% if is_state("input_select.transport", "Car") %} {{40|float}} {% elif is_state("input_select.transport", "Bike") %} {{40|float}} {% endif %}'
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.radio_on_hour
        value: '{% if is_state("input_select.transport", "Car") %} {{5|float}} {% elif is_state("input_select.transport", "Bike") %} {{5|float}} {% endif %}'
    - service: input_slider.select_value
      data_template:
        entity_id: input_slider.radio_on_minute
        value: '{% if is_state("input_select.transport", "Car") %} {{55|float}} {% elif is_state("input_select.transport", "Bike") %} {{50|float}} {% endif %}'

- alias: auto_light_on
####################
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.light_on_time.state }}'
  condition:
    condition: numeric_state
    entity_id: sensor.indoor_light
    below: 30
  action:
    - service: scene.turn_on
      entity_id: scene.morning_1

- alias: auto_radio_on
####################
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.radio_on_time.state }}'
  action:
    - service: media_player.clear_playlist
      data:
        entity_id: media_player.MPD
    - service: media_player.play_media
      data:
        entity_id: media_player.MPD
        media_content_type: playlist
        media_content_id: P7
    - service: media_player.volume_set
      data:
        entity_id: media_player.MPD
        volume_level: 0.07

- alias: morning_preset_weekday
####################
  trigger:
    platform: time
    hours: 12
    minutes: 0
    seconds: 0
  condition:
    condition: time
    weekday:
      - sun
  action:
   - service: homeassistant.turn_on
     entity_id: group.morning
   - service: input_select.select_option
     data:
       entity_id: input_select.transport
       option: "Bike"

- alias: morning_preset_weekend
####################
  trigger:
    platform: time
    hours: 12
    minutes: 0
    seconds: 0
  condition:
    condition: time
    weekday:
      - fri
  action:
   - service: homeassistant.turn_off
     entity_id: group.morning

- alias: motion
####################
  trigger:
    platform: mqtt
    topic: "motion/test"
    payload: "1"
  action:
   service: device_tracker.see
   data:
     dev_id: motion


- alias: temp
####################
  trigger:
    platform: state
    entity_id: sensor.aarhus_temperature
  action:
    service: mqtt.publish
    data_template:
      topic: "outdoor/temperature"
      payload_template: '{{ states.sensor.aarhus_temperature.state | round(0) }}'
      retain: "true"

- alias: In bed
####################
  trigger:
    - platform: state
      entity_id: sensor.bed_sensor_1
#      from: '0'
      to: '1'
      for:
        minutes: 1
        
    - platform: state
      entity_id: sensor.bed_sensor_2
      #~ from: '0'
      to: '1'
      for:
        minutes: 1
        
    - platform: state
      entity_id: sensor.bed_sensor_3
      #~ from: '0'
      to: '1'
      for:
        minutes: 1
        
  action:
    service: input_boolean.turn_on
    data:
      entity_id: input_boolean.in_bed

- alias: Out of bed
####################
  trigger:
    - platform: state
      entity_id: sensor.bed_sensor_1
      #~ from: '1'
      to: '0'
      for:
        seconds: 30
        
    - platform: state
      entity_id: sensor.bed_sensor_2
      #~ from: '1'
      to: '0'
      for:
        seconds: 30
        
    - platform: state
      entity_id: sensor.bed_sensor_3
      #~ from: '1'
      to: '0'
      for:
        seconds: 30
        
  condition:
    - condition: state
      entity_id: sensor.bed_sensor_1
      state: '0'
    - condition: state
      entity_id: sensor.bed_sensor_2
      state: '0'
    - condition: state
      entity_id: sensor.bed_sensor_3
      state: '0'
    
  action:
    service: input_boolean.turn_off
    data:
      entity_id: input_boolean.in_bed

- alias: Goodnight
####################
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    from: 'off'
    to: 'on'
  action:
    service: script.turn_on
    entity_id: script.goodnight


- alias: Goodnight light
####################
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: light.mood
      state: 'on'
  action:
    service: script.turn_on
    entity_id: script.goodnight_light

- alias: Lights on
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_1/hold"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) > 30 }}'
  action:
    service: scene.turn_on
    entity_id: scene.full_light

- alias: Lights off
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_1/repeat"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) == 2 }}'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Desk light
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_2/hold"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) < 30 }}'
  action:
    service: light.toggle
    entity_id: light.desk

- alias: Castrol light
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_3/hold"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) < 30 }}'
  action:
    service: light.toggle
    entity_id: light.castrol


- alias: Random
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_5/repeat"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) == 3 }}'
  action:
    service: light.turn_on
    data:
      entity_id: light.mood
      effect: Random
    

- alias: Red alert
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_5/repeat"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) == 2 }}'
  action:
    service: scene.turn_on
    entity_id: scene.red_alert


- alias: Irrigation
####################
  trigger:
    platform: time
    hours: '/2'
    minutes: 0
    seconds: 0
  condition:
    condition: and
    conditions:
      - condition: time
        after: "10:00:00"
        before: "20:00:00"
      - condition: template
        value_template: '{{ states.sensor.aarhus_precip_intensity.state | round(0) < 1 }}'
  action:
   - service: script.turn_on
     entity_id: script.irrigation


- alias: Test to speech
####################
  trigger:
    platform: mqtt
    topic: "buttons/button_4/hold"
  condition:
    - condition: template
      value_template: '{{ trigger.payload | round(0) < 30 }}'
  action:
   - service: script.turn_on
     entity_id: script.weather_presentation
