# Weather Prediction
#~ - platform: yr
  #~ name: Aarhus
  #~ monitored_conditions:
  #~ - temperature
  #~ - dewpointTemperature
  #~ - precipitation
  #~ - humidity

- platform: darksky
  name: Aarhus
  api_key: 6f2858bbbaaeb4b9f04fd0e3baa18240
  update_interval:
    minutes: 5
  monitored_conditions:
    - temperature
    - temperature_max
    - temperature_min
    - apparent_temperature
    - apparent_temperature_min
    - apparent_temperature_max
    - precip_intensity
    - precip_intensity_max
    - wind_speed
    - wind_bearing
    - humidity
    - minutely_summary
    - hourly_summary

# Time "sensors"
- platform: template
  sensors:
    time:
      friendly_name: "CurTime"
      value_template: '{{ now().strftime("%-H:%M") }}'
    light_on_time:
      friendly_name: "Light on"
      value_template: '{{ states.input_slider.light_on_hour.state | int }}:{% if states.input_slider.light_on_minute.state | length == 3 %}0{% endif %}{{ states.input_slider.light_on_minute.state | int}}'
    radio_on_time:
      friendly_name: "Radio on"
      value_template: '{{ states.input_slider.radio_on_hour.state | int }}:{% if states.input_slider.radio_on_minute.state | length == 3 %}0{% endif %}{{ states.input_slider.radio_on_minute.state | int}}'

# Temperature sensors
- platform: mqtt
  name: "Indoor temperature"
  state_topic: "indoor/temperature"
  unit_of_measurement: '°C'

#~ - platform: mqtt
  #~ name: "Bathroom temperature"
  #~ state_topic: "bathroom/temperature"
  #~ unit_of_measurement: '°C'

# Humidity sensors
- platform: mqtt
  name: "Indoor humidity"
  state_topic: "indoor/humidity"
  unit_of_measurement: '%'

#~ - platform: mqtt
  #~ name: "Bathroom humidity"
  #~ state_topic: "bathroom/humidity"
  #~ unit_of_measurement: '%'
  
# Light sensors
- platform: mqtt
  name: "Light level"
  state_topic: "lightlevel/west"
  unit_of_measurement: '%'

# Bed sensors
- platform: mqtt
  name: "Bed sensor value"
  state_topic: "bed/touch/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 1 value"
  state_topic: "bed/touch/0/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 2 value"
  state_topic: "bed/touch/1/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 3 value"
  state_topic: "bed/touch/2/value"
  unit_of_measurement: '-'

# Utility sensors
- platform: mqtt
  name: "Power"
  state_topic: "meter/power"
  unit_of_measurement: 'W'

# Motion sensors
#~ - platform: mqtt
  #~ name: PIR
  #~ state_topic: "motion/test"
  
- platform: mqtt
  name: PIR_length
  state_topic: "motion/length"
  unit_of_measurement: 's'
