# Weather Prediction
- platform: yr
  name: Aarhus
  monitored_conditions:
  - temperature
  - dewpointTemperature
  - precipitation
  - humidity

# Time "sensors"
- platform: template
  sensors:
    time:
      friendly_name: "CurTime"
      value_template: '{{ now().strftime("%-H:%M") }}'
    light_on_time:
      friendly_name: "Light on"
      value_template: '{{ states.input_slider.light_on_hour.state | int }}:{% if states.input_slider.light_on_minute.state | length == 3 %}0{% endif %}{{ states.input_slider.light_on_minute.state | int}}'
    radio_on_time:
      friendly_name: "Radio on"
      value_template: '{{ states.input_slider.radio_on_hour.state | int }}:{% if states.input_slider.radio_on_minute.state | length == 3 %}0{% endif %}{{ states.input_slider.radio_on_minute.state | int}}'

# Temperature sensors
- platform: mqtt
  name: "Indoor temperature"
  state_topic: "indoor/temperature"
  unit_of_measurement: '°C'

#~ - platform: mqtt
  #~ name: "Bathroom temperature"
  #~ state_topic: "bathroom/temperature"
  #~ unit_of_measurement: '°C'

# Humidity sensors
- platform: mqtt
  name: "Indoor humidity"
  state_topic: "indoor/humidity"
  unit_of_measurement: '%'

#~ - platform: mqtt
  #~ name: "Bathroom humidity"
  #~ state_topic: "bathroom/humidity"
  #~ unit_of_measurement: '%'
  
# Light sensors
- platform: mqtt
  name: "Indoor light"
  state_topic: "indoor/light"
  unit_of_measurement: '%'

# Bed sensors
- platform: mqtt
  name: "Bed sensor 1"
  state_topic: "bath/touch/0"

- platform: mqtt
  name: "Bed sensor 1 value"
  state_topic: "bath/touch/0/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 1 base"
  state_topic: "bath/touch/0/base"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 2"
  state_topic: "bath/touch/1"

- platform: mqtt
  name: "Bed sensor 2 value"
  state_topic: "bath/touch/1/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 2 base"
  state_topic: "bath/touch/1/base"
  unit_of_measurement: '-'
  
- platform: mqtt
  name: "Bed sensor 3"
  state_topic: "bath/touch/2"

- platform: mqtt
  name: "Bed sensor 3 value"
  state_topic: "bath/touch/2/value"
  unit_of_measurement: '-'

- platform: mqtt
  name: "Bed sensor 3 base"
  state_topic: "bath/touch/2/base"
  unit_of_measurement: '-'

# Utility sensors
- platform: mqtt
  name: "Power"
  state_topic: "meter/power"
  unit_of_measurement: 'W'

# Motion sensors
#- platform: mqtt
#  name: PIR
#  state_topic: "motion/test"
